version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    networks: 
      - node-network
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/db:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    networks: 
      - node-network
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  node-network:
    driver: bridge